changelog:
  sections:
  - title: ":star: New Features"
    labels: ["enhancement"]
  - title: ":lady_beetle: Bug Fixes"
    labels: ["bug"]
  - title: ":notebook_with_decorative_cover: Documentation"
    labels: ["documentation"]
  - title: ":hammer: Dependency Upgrades"
    labels: ["dependency-upgrade"]
  - title: ":star: All pull requests"
    labels:
      - '*'
