template: |
    ## Highlights
    Major updates in this release include:
    - 🚀 Features
    - 🐛 Bug Fixes
    - 🛠️ Maintenance tasks

    ## What's Changed
    ${{ changes }}

    ## Contributors
    Thanks to the following people who contributed to this release:
    ${{ contributors }}
