name: Increment, Publish, and Deploy

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Select version type (major, minor, patch)'
        required: false
        type: choice
        options:
          - major
          - minor
          - patch
        default: minor # Default selection if none is provided

  # Scheduled triggers
  schedule:
    - cron: '30 7 * * 1-5' # 1 PM IST (7:30 AM UTC) every weekday
    - cron: '30 14 * * 1-5' # 8 PM IST (2:30 PM UTC) every weekday

jobs:
  increment-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Fetch Latest Tags
      - name: Fetch Latest Tags
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      # Step 3: Check for New Commits
      - name: Check for New Commits
        run: |
          latest_commit=$(git rev-parse HEAD)
          tag_commit=$(git rev-list -n 1 ${{ env.latest_tag }})
          if [ "$latest_commit" = "$tag_commit" ]; then
            echo "No new commits since the last tag (${env.latest_tag}). Exiting workflow."
            exit 0
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Detect Merges and Determine Version Bump
      - name: Detect Merges and Determine Version Bump
        id: detect_merge
        run: |
          chmod +x .github/scripts/detect_version_bump.sh
          version_type=$(.github/scripts/detect_version_bump.sh ${{ env.latest_tag }})
          echo "version_type=$version_type" >> $GITHUB_ENV
          echo "Detected version type: $version_type"

      # Step 5: Increment Version
      - name: Increment Version
        id: new_version
        run: |
          latest_tag="${{ env.latest_tag }}"
          latest_tag=${latest_tag#v} # Remove 'v' prefix if it exists
          IFS='.' read -r major minor patch <<< "$latest_tag"
          version_type=${{ github.event.inputs.version_type || env.version_type }}
          if [ "$version_type" == "major" ]; then
            major=$((major+1))
            minor=0
            patch=0
          elif [ "$version_type" == "minor" ]; then
            minor=$((minor+1))
            patch=0
          else
            patch=$((patch+1))
          fi
          new_version="v$major.$minor.$patch"
          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "Next version: $new_version"

      # Step 6: Create and Push New Tag
      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.new_version }}
          git push origin ${{ env.new_version }}
          echo "Published tag: ${{ env.new_version }}"

      # Step 7: Generate and Publish GitHub Release
      - name: Publish GitHub Release with Generated Notes
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_version }}
          release_name: "Release ${{ env.new_version }}"
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Build the Project
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build
        env:
          NODE_ENV: production

      # Step 9: Deploy to CDN
      - name: Deploy to CDN
        run: |
          echo "Deployed version ${{ env.new_version }} to the CDN."

      # Step 10: Output New Version
      - name: Output New Version
        run: echo "Successfully deployed version ${{ env.new_version }} to the CDN."
