name: Generate Release Note

on:
  milestone:
    types: [closed]

jobs:
  generate-release-note:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Generate Release Note
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        MILESTONE_NUMBER: ${{ github.event.milestone.number }}
        MILESTONE_TITLE: ${{ github.event.milestone.title }}
      run: |
        bash .github/scripts/generate-release-note.sh

    - name: Upload Release Note
      uses: actions/upload-artifact@v3
      with:
        name: release-note
        path: release-note.txt
