on: 
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - name: Release notes generator
      uses: Decathlon/release-notes-generator-action@v3.1.6 
      env:
        GITHUB_TOKEN: ${{ secrets.my_pat }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "true"
        

    - name: Upload release notes as an attachment
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
          name: release-notes
          path: temp_release_notes/
          retention-days: 30