name: Generate Release Note

on:
  milestone:
    types: [closed]

jobs:
  generate-release-note:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Generate Release Note
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO: ${{ github.repository }}
        MILESTONE_NUMBER: ${{ github.event.milestone.number }}
        MILESTONE_TITLE: ${{ github.event.milestone.title }}
      run: |
        bash .github/scripts/generate-release-note.sh

    - name: Read Release Note
      id: read_release_note
      run: |
        release_note=$(cat .github/release-note.txt)
        echo "::set-output name=release_note::$release_note"

    - name: Create Pull Request
      id: pr1
      run: |
        echo "Creating PR from demo-branch to master..."
        gh pr create --base master --head demo-branch --title "Merge ``demo-branch`` into ``master``" --body "${{ steps.read_release_note.outputs.release_note }}"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
