name: Revert and Redeploy Specific Version

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag version to deploy (e.g., v1.0.4)'
        required: true

jobs:
  revert-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch Tags and Checkout Specific Tag
      - name: Fetch and Checkout Specific Tag
        run: |
          git fetch --tags
          git checkout ${{ github.event.inputs.tag_name }}

      # Step 3: Validate Checked-Out Tag
      - name: Validate Checked-Out Tag
        run: |
          checked_out_tag=$(git describe --tags)
          if [ "$checked_out_tag" != "${{ github.event.inputs.tag_name }}" ]; then
            echo "Error: Checked-out tag ($checked_out_tag) does not match the input tag (${{ github.event.inputs.tag_name }})."
            exit 1
          fi
        shell: bash

      # Step 4: Build and Deploy
      - name: Install Dependencies and Build
        run: |
          npm install
          npm run build

      - name: Write Deployment Metadata
        run: |
          echo "version: ${{ github.event.inputs.tag_name }}" > ./build/deployment-metadata.json
          echo "timestamp: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> ./build/deployment-metadata.json

      - name: Deploy to CDN
        env:
          CDN_API_KEY: ${{ secrets.CDN_API_KEY }}
        run: |
          deploy_to_cdn ./build
          echo "Deployed version ${{ github.event.inputs.tag_name }} with metadata."

      # Step 5: Log Deployed Version
      - name: Log Deployed Version
        run: echo "Successfully deployed version ${{ github.event.inputs.tag_name }}"
