name: Revert and Redeploy Specific Version

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag version to deploy (e.g., v1.0.1, v1.0.2)'
        required: true

jobs:
  revert-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch Tags and Checkout Specific Tag
      - name: Fetch and Checkout Specific Tag
        run: |
          git fetch --tags --force
          if ! git rev-parse "${{ github.event.inputs.tag_name }}" >/dev/null 2>&1; then
            echo "Error: Tag ${{ github.event.inputs.tag_name }} does not exist in the repository."
            exit 1
          fi
          git checkout ${{ github.event.inputs.tag_name }}

      # Step 3: Validate Checked-Out Tag
      - name: Validate Checked-Out Tag
        run: |
          checked_out_tag=$(git describe --tags --exact-match 2>/dev/null || git rev-parse HEAD)
          if [ "$checked_out_tag" != "${{ github.event.inputs.tag_name }}" ]; then
            echo "Error: Checked-out tag ($checked_out_tag) does not match the input tag (${{ github.event.inputs.tag_name }})."
            exit 1
          fi
        shell: bash

      # Step 5: Write Deployment Metadata
      - name: Write Deployment Metadata
        run: |
          mkdir -p artifacts
          echo "{ \"version\": \"${{ github.event.inputs.tag_name }}\", \"commit\": \"$(git rev-parse HEAD)\", \"deployed_by\": \"github-actions[bot]\", \"deployed_at\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\" }" > artifacts/deployment-metadata.json


      # Step 8: Push Deployment Metadata to Logs Branch
      - name: Push Deployment Metadata to Logs Branch
        if: env.skip_deployment == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Remove any uncommitted or conflicting files to ensure a clean state
          git reset --hard
          git clean -fdx

          # Ensure the branch exists locally
          git fetch origin deployment-logs:deployment-logs || true
          if ! git rev-parse --verify deployment-logs >/dev/null 2>&1; then
            git checkout -b deployment-logs
          else
            git checkout deployment-logs
          fi

          # Copy deployment metadata to the root directory
          mkdir -p artifacts
          if [ -f artifacts/deployment-metadata.json ]; then
            cp artifacts/deployment-metadata.json .
            git add deployment-metadata.json
            git commit -m "Track deployment of version ${{ env.new_version }} to production" || echo "No changes to commit"
          else
            echo "Warning: Deployment metadata file not found. Skipping commit."
            exit 0
          fi

          # Force push the branch
          git push origin deployment-logs --force



      # Step 7: Upload Deployment Metadata as Artifact
      - name: Upload Deployment Metadata as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: deployment-metadata
          path: artifacts/deployment-metadata.json

      # Step 8: Log Deployed Version
      - name: Log Deployed Version
        run: echo "Successfully deployed version ${{ github.event.inputs.tag_name }}"
