name: Update Existing Tag Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Enter the existing tag version to update (e.g., v1.0.4)'
        required: true

jobs:
  update-existing-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Fetch All Tags
      - name: Fetch Tags
        run: git fetch --tags

      # Step 3: Verify Specified Tag Exists
      - name: Verify Tag Exists
        run: |
          if ! git rev-parse ${{ github.event.inputs.tag_name }} >/dev/null 2>&1; then
            echo "Error: Specified tag does not exist."
            exit 1
          fi
        shell: bash

      # Step 4: Update Existing Release
      - name: Update Existing Release
        uses: actions/github-script@v6
        with:
          script: |
            const tagName = "${{ github.event.inputs.tag_name }}";

            // Fetch all releases
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            // Find the release associated with the tag
            const existingRelease = releases.data.find(release => release.tag_name === tagName);

            if (!existingRelease) {
              throw new Error(`No release found for tag: ${tagName}`);
            }

            // Update the existing release
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: existingRelease.id,
              name: `Updated Release for ${tagName}`,
              body: `This is an updated release for the tag ${tagName}.`,
            });

            console.log(`Updated release for tag: ${tagName}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Output Success Message
      - name: Output Success
        run: echo "The release for tag ${{ github.event.inputs.tag_name }} has been successfully updated."
